articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),

    path('create/', views.create, name='create'),

    path('<int:id>/delete/', views.delete, name='delete'),

    path('<int:id>/update/', views.update, name='update'),

]

modelForm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = '__all__'

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles' : articles,
    }

    return render(request, 'index.html', context)


def detail(request ,id):
    article = Article.objects.get(id=id)

    context = {
        'article' : article,
    }

    return render(request, 'detail.html', context)


def create(request):
    # 모든 경우의 수
    # 1. GET : From 만들어서 html 문서를 사용자에게 리턴
    # 2. POST invalid data : 데이터 검증에 실패한 경우
    #    => 검증에 성공한 데이터만 가지고 Form을 만들어 html 문서를 사용자에게 리턴
    # 3. Post valid data : 데이터 검증에 성공한 경우
    #    => DB에 데이터 저장 후 detail로 redirect


# =====================================================


    # 5. POST 요청 (데이터가 잘못 들어온 경우)
    # 10. POST 요청 (데이터가 잘 들어온 경우)
    if request.method == 'POST':
        # 6. Form에 사용자가 입력한 정보(x)를 담아서 Form을 생성
        # 11. Form에 사용자가 입력한 정보(o)를 담아서 Form을 생성
        form = ArticleForm(request.POST)
        # 7. Form을 검증 (검증에 실패, 코드 실행 불가)
        # 12. Form을 검증 (검증에 성공)
        if form.is_valid():
            # 13. Form을 저장하고 그 결과를 article 변수에 저장
            article = form.save()
            # 14. detail 페이지로 redirect
            return redirect('articles:detail', id=article.id)
        
        

# 1. GET 요청
    else:
        # 2. 비어있는 Form을 만들어서
        form = ArticleForm()

    # 3. context dict에 담고
    # 8. 검증에 실패한 Form을 context dict에 담고
    context = {
        'form' : form,
    }

    # 4. create.html을 랜더링
    # 9. create.html을 랜더링
    return render(request, 'create.html', context)
        

def delete(request, id):
    article = Article.objects.get(id=id)

    article.delete()

    return redirect('articles:index')

def update(request, id):
    article = Article.objects.get(id=id)

    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)

        if form.is_valid():
            form.save()
            return redirect('articles:detail', id=id)

    else:
        form = ArticleForm(instance=article)

    context = {
        'form' : form,
    }

    return render(request, 'update.html', context)

articles/templates/create.html
{% extends 'base.html' %}

{% block body %}

    <form action="" method="POST">
        {% csrf_token %}

        {{form}}
        <input type="submit">

    </form>

{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>{{article.title}}</h1>
<p>{{article.content}}</p>
<p>{{article.created_at}}</p>
<p>{{article.updated_at}}</p>

<a href="{% url 'articles:update' id=article.id %}">update</a>
<a href="{% url 'articles:delete' id=article.id %}">delete</a>


{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>index</h1>

    {% for article in articles %}
        <p>{{article.title}}</p>
        <a href="{% url 'articles:detail' id=article.id %}">detail</a>

        <hr>
    {% endfor %}

{% endblock %}

articles/templates/update.html
{% extends 'base.html' %}

{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'articles:index' %}">Home</a>
    <a href="{% url 'articles:create' %}">Create</a>

    {% block body %}

    {% endblock %}

</body>
</html>